apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kube-state-metrics
  namespace: flux-system
spec:
  interval: 1m
  url: https://kubernetes.github.io/kube-state-metrics
