apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 5m
  chart:
    spec:
      chart: hashicorp/vault
      sourceRef:
        kind: HelmRepository
        name: hashicorp/vault
        namespace: flux-system
      version: "0.25.0"
