apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubevious
  namespace: kubevious
spec:
  interval: 5m
  chart:
    spec:
      chart: "kubevious/kubevious"
      sourceRef:
        kind: HelmRepository
        name: kubevious
        namespace: flux-system
      version: "1.2.1"
