apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: '2.18.0'
      sourceRef:
        kind: HelmRepository
        name: mojo2600
