apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus-service.prometheus:8083 # adjust this if your service name/namespace is different
  isDefault: true
