apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana
spec:
  ports:
  - port: 8082
    targetPort: 3000
  selector:
    app: grafana
  type: NodePort # Expose outside the cluster
