---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: starboard-operator
  namespace: starboard-system
spec:
  chart:
    spec:
      chart: aqua/starboard-operator
      sourceRef:
        kind: HelmRepository
        name: starboard-operator
        namespace: flux-system
      version: 0.15.15
  interval: 1m0s
