apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: localstack
  namespace: localstack
spec:
  interval: 5m
  chart:
    spec:
      chart: localstack
      sourceRef:
        kind: HelmRepository
        name: localstack
        namespace: flux-system
      version: "0.6.5"
