apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: prometheus
spec:
  ports:
  - port: 8083
    targetPort: 9090
  selector:
    app: prometheus
  type: NodePort # Expose outside the cluster
