---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    type: nfs
spec:
  capacity:
    storage: 5Gi  # Adjust the size as needed
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume1/Proxmox
    server: 192.168.1.107
  persistentVolumeReclaimPolicy: Retain
