apiVersion: v1
kind: LimitRange
metadata:
  name: media-service-limits
  namespace: media-service
spec:
  limits:
  - default:
      memory: "512Mi"
      cpu: "500m"
    defaultRequest:
      memory: "256Mi"
      cpu: "250m"
    type: Container
