---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: vault
      version: '0.13.0'  # specify the version you'd like to use
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  values:
    server:
      standalone:
        enabled: true
      ui:
        enabled: true
